/**
 * Made by shadow
 * Aira.js
 * Aira is a small artificial intelligence library that is currently under development.
 */




//Neuron//
class Neuron {
    constructor() {
    this.weights = Array.from({length: 3}, () => Math.random())
    this.bias = Math.random()
  }

  process(inputs) {
    let sum = 0;
    for (let i = 0; i < inputs.length; i++) {
      sum += inputs[i] * this.weights[i]
    }
    return 1 / (1 + Math.exp(-(sum + this.bias))) 
  }
    train(inputs, target, learningRate = 0.1) {
    const output = this.process(inputs)
    const error = target - output
    
      
    for (let i = 0; i < this.weights.length; i++) {
      this.weights[i] += learningRate * error * inputs[i]
    }
    this.bias += learningRate * error
  }
}

let layer = []
for (let i = 0; i < 100; i++) {
  layer.push(new Neuron())
    
}
//Network//
class NeuralNetwork {

    constructor(inputSize,hiddenSize,outputSize) {
      this.hiddenLayer = Array.from({length: hiddenSize}, () => new Neuron(inputSize))
      this.outputLayer = new Neuron(hiddenSize)
    }
    
    predict(inputs) {
      const hiddenOutputs=this.hiddenLayer.map(Neuron => Neuron.process(inputs))
      return this.outputLayer.process(hiddenOutputs)
    }
}

class Activation {
    static relu(x) {return Math.max(0,x)}
    static tanh(x) {return Math.tanh(x)}
    static softmax(values) {}
}

function errorMeasurement(predicted,actual) {

   return predicted.reduce((sum, p, i) => sum + Math.pow(p - actual[i], 2), 0) / predicted.length


}
    //Tokenizg
    function Tokenizer(input) {

    input = input.toLowerCase();


    const wordRegex = /[a-zığüşöç0-9]+/gi;

    const tokens = input.match(wordRegex)

    return tokens || []
}
const network = new NeuralNetwork
const neuron = new Neuron
const activate = new Activation


const vocab = {
    //TR
 selam:2,
  merhaba:2,
  nasılsın:1,
  iyimisin:1,
  napıyorsun:2,
  hey:1,
  muhteşem: 1,
  harikulade: 1,
  olağanüstü: 1,
  etkileyici: 1,
  hayran: 1,
  aydınlatıcı: 1,
  sevecen: 1,
  yardımsever: 1,
  başarılı: 1,
  güvenilir: 1,
  umut_verici: 1,
  düşünceli: 1,
  saygılı: 1,
  samimi: 1,
  cesaretlendirici: 1,
  iyimser: 1,
  duyarlı: 1,
  alçakgönüllü: 1,
  zarif: 1,
  dostane: 1,
  içten: 1,
  üretken: 1,
  motive_edici: 1,
  hoşgörülü: 1,
  anlayışlı: 1,
  dürüst: 1,
  fedakâr: 1,
  ilham_verici: 1,
  yetenekli: 1,
  istikrarlı: 1,
  pozitif: 1,
  çalışkan: 1,
  sabırlı: 1,
  kararlı: 1,
  özverili: 1,
  sevgi_dolu: 1,
  umutlu: 1,
  verimli: 1,
  dikkatli: 1,
  nazik: 1,
  saygın: 1,
  tutkulu: 1,
  adil: 1,
  yaratıcı: 1,
  bilgili: 1,
  vicdanlı: 1,
  disiplinli: 1,
  sempatik: 1,
  kibar: 1,
  gurur_verici: 1,
  cömert: 1,
  mantıklı: 1,
  olgun: 1,
  coşkulu: 1,
  duygu_dolu: 1,
  güvenli: 1,
  umutlandırıcı: 1,
  sağlam: 1,
  üretici: 1,
  destekleyici: 1,
  barışçıl: 1,
  istikrarlı: 1,
  karizmatik: 1,
  etkileyici: 1,
  parlak: 1,
  gelişmiş: 1,
  becerikli: 1,
  huzurlu: 1,
  anlayışlı: 1,
  tatmin_edici: 1,
  canlı: 1,
  dinamik: 1,
  güven_verici: 1,
  sevindirici: 1,
  keyifli: 1,
  değerli: 1,
  umutlu: 1,
  huzur_verici: 1,
  özenli: 1,
  duygu_yüklü: 1,
  neşeli: 1,
  memnuniyet: 1,
  muhteşem: 1,
harikulade: 1,
olağanüstü: 1,
etkileyici: 1,
aydınlık: 1,
parlak: 1,
ışıl_ışıl: 1,
sevecen: 1,
yardımsever: 1,
samimi: 1,
dostane: 1,
nazik: 1,
kibar: 1,
saygılı: 1,
düşünceli: 1,
alçakgönüllü: 1,
hoşgörülü: 1,
sabırlı: 1,
çalışkan: 1,
özverili: 1,
fedakâr: 1,
yetenekli: 1,
bilgili: 1,
akıllı: 1,
zeki: 1,
disiplinli: 1,
üretken: 1,
verimli: 1,
motive_edici: 1,
umut_verici: 1,
ilham_verici: 1,
iyimser: 1,
coşkulu: 1,
dinamik: 1,
canlı: 1,
şen: 1,
neşeli: 1,
pozitif: 1,
güleryüzlü: 1,
güvenilir: 1,
dürüst: 1,
vicdanlı: 1,
sağlam: 1,
kararlı: 1,
istikrarlı: 1,
tutarlı: 1,
mantıklı: 1,
olgun: 1,
cömert: 1,
zarif: 1,
huzurlu: 1,
huzur_verici: 1,
sevgi_dolu: 1,
şefkatli: 1,
merhametli: 1,
bağışlayıcı: 1,
dost_kalpli: 1,
sıcakkanlı: 1,
canayakın: 1,
girişken: 1,
cesur: 1,
özgüvenli: 1,
lider_ruhu: 1,
vizyoner: 1,
yaratıcı: 1,
hayal_gücü_yüksek: 1,
becerikli: 1,
usta: 1,
analitik: 1,
çözüm_odaklı: 1,
pratik: 1,
ince: 1,
duyarlı: 1,
şefkat_dolu: 1,
özenli: 1,
titiz: 1,
düzenli: 1,
planlı: 1,
gönüllü: 1,
iyiliksever: 1,
erdemli: 1,
ahlaklı: 1,
saygın: 1,
güçlü: 1,
dirençli: 1,
dayanıklı: 1,
kararlı_ruhlu: 1,
ışık_dolu: 1,
umut_saçan: 1,
hevesli: 1,
gayretli: 1,
güçlendirici: 1,
toparlayıcı: 1,
dengeli: 1,
duygu_dolu: 1,
sevindirici: 1,
tatmin_edici: 1,
barışçıl: 1,
yumuşak: 1,
latif: 1,
naziklik: 1,
şahane: 1,
olağanüstülük: 1,
kaliteli: 1,
kusursuz: 1,
güven_verici: 1,
sıcacık: 1,
umutlu: 1,
değerli: 1,
takdir_edilen: 1,
özgün: 1,
onurlu: 1,
erdem: 1,
duru: 1,
ferah: 1,
aydınlatıcı: 1,
parıltılı: 1,
temiz: 1,
gelişmiş: 1,
bilge: 1,
ustaca: 1,
bağımsız: 1,
özgür: 1,
yapıcı: 1,
nezaketli: 1,
duyarlılık: 1,
sadık: 1,
dost_canlısı: 1,
sevilen: 1,
şefkat: 1,
anlayışlı: 1,
hoş: 1,
uyumlu: 1,
prensipli: 1,
dürüstlük: 1,
adil: 1,
tutkulu: 1,
güçlü_ruhlu: 1,
öğrenmeye_açık: 1,
gelişime_açık: 1,
net: 1,
samimiyet_dolu: 1,
parıldayan: 1,
gönül_alıcı: 1,
insancıl: 1,
yürekli: 1,
yansız: 1,
onurluluk: 1,
haysiyetli: 1,
güçlü_karakterli: 1,
huzurluluk: 1,
şevkli: 1,
dirayetli: 1,
çözümcü: 1,
aktif: 1,
atılgan: 1,


  hayal_kırıklığı: 0,
  saygısız: 0,
  ilgisiz: 0,
  güvenilmez: 0,
  düşüncesiz: 0,
  sorumsuz: 0,
  kötü_niyetli: 0,
  bencil: 0,
  kibirli: 0,
  karamsar: 0,
  umutsuz: 0,
  dağınık: 0,
  başarısız: 0,
  üzücü: 0,
  tatsız: 0,
  çirkin: 0,
  kaba: 0,
  sinirli: 0,
  öfkeli: 0,
  huysuz: 0,
  tembel: 0,
  dikkatsiz: 0,
  alaycı: 0,
  kıskanç: 0,
  çıkarcı: 0,
  şüpheci: 0,
  huzursuz: 0,
  saldırgan: 0,
  ilgisiz: 0,
  korkak: 0,
  pişman: 0,
  zalim: 0,
  aksi: 0,
  kaba_saba: 0,
  kırıcı: 0,
  üzgün: 0,
  mutsuz: 0,
  melankolik: 0,
  nefret_dolu: 0,
  önyargılı: 0,
  üzütlü: 0,
  değersiz: 0,
  başarısızlık: 0,
  sinir_boğucu: 0,
  sıkıcı: 0,
  acımasız: 0,
  çaresiz: 0,
  korkunç: 0,
  iğrenç: 0,
  rahatsız: 0,
  utanç: 0,
  rezil: 0,
  tatsız: 0,
  anlamsız: 0,
  moral_bozan: 0,
  felaket: 0,
  beceriksiz: 0,
  üzgünlük: 0,
  perişan: 0,
  umutsuzluk: 0,
  çaresizlik: 0,
  hayalci: 0,
  sevilmeyen: 0,
  özensiz: 0,
  kederli: 0,
  suçlu: 0,
  beceriksizlik: 0,
  sorunlu: 0,
  zayıf: 0,
  eksik: 0,
  moralsiz: 0,
  kötü: 0,
  kötü: 0,
çirkin: 0,
iğrenç: 0,
berbat: 0,
tatsız: 0,
sinirli: 0,
öfkeli: 0,
huysuz: 0,
kaba: 0,
kaba_saba: 0,
saygısız: 0,
bencil: 0,
çıkarcı: 0,
kibirli: 0,
gurursuz: 0,
düşüncesiz: 0,
umutsuz: 0,
karamsar: 0,
şikâyetçi: 0,
kötümser: 0,
soğuk: 0,
duygusuz: 0,
acımasız: 0,
zalim: 0,
kırıcı: 0,
alaycı: 0,
kıskanç: 0,
şüpheci: 0,
güvenilmez: 0,
sorumsuz: 0,
dağınık: 0,
dikkatsiz: 0,
özensiz: 0,
tembel: 0,
isteksiz: 0,
umursamaz: 0,
ilgisiz: 0,
rahatsız: 0,
çirkin_sözlü: 0,
tutarsız: 0,
mantıksız: 0,
saçma: 0,
kötü_niyetli: 0,
nefret_dolu: 0,
önyargılı: 0,
korkak: 0,
çekingen: 0,
saldırgan: 0,
sert: 0,
acı: 0,
üzgün: 0,
mutsuz: 0,
melankolik: 0,
kederli: 0,
perişan: 0,
çaresiz: 0,
umutsuzluk: 0,
üzücü: 0,
moral_bozan: 0,
bozucu: 0,
kırılgan: 0,
tutarsızlık: 0,
pişman: 0,
rahatsız_edici: 0,
felaket: 0,
başarısız: 0,
başarısızlık: 0,
beceriksiz: 0,
beceriksizlik: 0,
zayıf: 0,
eksik: 0,
yetersiz: 0,
kötücül: 0,
pis: 0,
kirli: 0,
rahatsızlık_verici: 0,
üzüntülü: 0,
üzücü_sözlü: 0,
motivasyonsuz: 0,
isteksizlik: 0,
soğuk_kanlı: 0,
katı: 0,
aşırı: 0,
sert_sözlü: 0,
bağırgan: 0,
dengesiz: 0,
karışık: 0,
karmaşık: 0,
problemli: 0,
sıkıcı: 0,
yavan: 0,
anlamsız: 0,
boş: 0,
ruhsuz: 0,
duygusuzluk: 0,
zorluklu: 0,
çöküş: 0,
kayıp: 0,
bitkin: 0,
yorgun: 0,
bezgin: 0,
gamsız: 0,
sorunlu: 0,
acımasızlık: 0,
küstah: 0,
saygısızlık: 0,
soğukkanlılık: 0,
gaddar: 0,
nankör: 0,
ihanetkâr: 0,
pişkin: 0,
tahammülsüz: 0,
öfke_dolu: 0,
çarpık: 0,
çarpık_düşünceli: 0,
kötü_kalp: 0,
buz_gibi: 0,
ürkek: 0,
tutuk: 0,
çekingence: 0,
bezdirici: 0,
kör: 0,
kör_bakışlı: 0,
acıtan: 0,
acı_dolu: 0,
huzursuz: 0,
utangaç: 0,
sıkıntılı: 0,
bıkmış: 0,
gergin: 0,
kısa_fuse: 0,
umut_ışıltılı: 1,
parlak_zihinli: 1,
duygu_ışığı: 1,
huzur_dolu: 1,
gülümseyen_yüz: 1,
nazik_sözlü: 1,
kucaklayıcı: 1,
dost_ruhlu: 1,
akılcı_düşünen: 1,
cesur_adım: 1,
kararlı_akıl: 1,
aydınlık_bilinç: 1,
öngörülü: 1,
uyanık: 1,
aktif_zihin: 1,
sistemli: 1,
erdem_dolu: 1,
mükemmel: 1,
ilerici: 1,
yenilikçi: 1,
özgür_fikirli: 1,
canlandırıcı: 1,
neşelendiren: 1,
ilham_kaynağı: 1,
umut_sunan: 1,
gülümseten: 1,
dostça: 1,
güç_kaynağı: 1,
sakin: 1,
dingin: 1,
tatlı_sözlü: 1,
gönlü_zengin: 1,
ruhu_güzel: 1,
yüce_gönüllü: 1,
dost_yüzlü: 1,
samimi_yürek: 1,
ışıldayan: 1,
renkli: 1,
canlı_görüşlü: 1,
pozitif_enerjili: 1,
tasarımcı: 1,
yaratıcı_zihin: 1,
çözümcü_ruhu: 1,
yetenek_zengini: 1,
bilgi_dolu: 1,
sorumlu: 1,
güven_veren: 1,
şefkatli_düşünen: 1,
koruyucu: 1,
destek_veren: 1,
iyileştirici: 1,
umut_olmuş: 1,
ışık_kaynağı: 1,
sevecen_yürek: 1,
duygusal_zekalı: 1,
uyanık_zihin: 1,
etkili: 1,
özlü: 1,
özgüven: 1,
hızlı_düşünen: 1,
çevik: 1,
profesyonel: 1,
yetenek_ustası: 1,
bilgelerden: 1,
erdem_ışığı: 1,
dost_dolu: 1,
nazik_davranışlı: 1,
iyi_niyetli: 1,
saygı_dolu: 1,
huzur_sunan: 1,
mutluluk_saçan: 1,
şefkat_sunan: 1,
dengeleyen: 1,
çare_bulan: 1,
çözüm_getiren: 1,
yararlı_olan: 1,
kolaylaştırıcı: 1,
ruh_dengesi: 1,
umut_besleyen: 1,
güvenli_duruş: 1,
sağlam_irade: 1,
iradeli: 1,
öz_disiplinli: 1,
dürüst_tavırlı: 1,
temiz_karakter: 1,
hoşa_giden: 1,
nazik_beden_dili: 1,
tatlı_davranışlı: 1,
insan_sever: 1,
yardım_dolu: 1,
kalp_aydınlatıcı: 1,
eleştiriye_açık: 1,
sorumluluk_sahibi: 1,
kendine_güvenen: 1,
açık_fikirli: 1,
öğretici: 1,
özbilinçli: 1,
öğretmen_ruhlu: 1,
yumuşak_kalpli: 1,
sevecen_bakışlı: 1,
renkli_zihin: 1,
parlak_enerji: 1,
dostluk_dolu: 1,
derin_düşünceli: 1,
ilerlemeci: 1,
vizyon_dolusu: 1,
modern: 1,
çağdaş: 1,
kararlı_zihin: 1,
çalışma_disiplinli: 1,
işbitirici: 1,
özen_sunan: 1,
detaycı: 1,
uyum_getiren: 1,
esnek_fikirli: 1,
uygar: 1,
özgür_karakter: 1,
şefkat_veren: 1,
huzur_kaynağı: 1,
can_yoldaşı: 1,
eşsiz: 1,
özel: 1,
güç_kazandırıcı: 1,
şans_getiren: 1,
nezaket_veren: 1,
empatik: 1,
duygu_okuyan: 1,
yol_gösteren: 1,
ilham_veren_sözlü: 1,
aydın_kişilik: 1,
yüksek_frekanslı: 1,
etkili_davranışlı: 1,
işbirlikçi: 1,
sakinleştirici: 1,
kalp_ferahlatıcı: 1,
umut_ışığı: 1,
güç_veren_dokunuş: 1,
olumlu_enerji: 1,
renk_katan: 1,
aydın_zihin: 1,
öğüt_veren: 1,
ruhu_yüce: 1,
nazik_tavırlı: 1,
ruhsal_güçlü: 1,
akıl_kaynağı: 1,
uzman: 1,
yetişmiş: 1,
usta_zihinli: 1,
çevik_düşünceli: 1,
bilgi_kaynağı: 1,
medenî: 1,
adil_davranışlı: 1,
çözüm_sunan: 1,
toparlayıcı_ruh: 1,
temiz_sözlü: 1,
dürüst_bilinçli: 1,
kalp_iyisi: 1,
saf_iyilik: 1,
aydınlık_kalp: 1,

korkunç: 0,
berbat_ruhlu: 0,
iğreti: 0,
uygunsuz: 0,
rahatsız_eden: 0,
ürkütücü: 0,
zayıf_karakterli: 0,
bozuk: 0,
hatalı: 0,
çarpık_karakter: 0,
kötü_sözlü: 0,
sataşan: 0,
edepsiz: 0,
bozguncu: 0,
kırıcı_sözlü: 0,
darmadağınık: 0,
çamurlu: 0,
kir_paslı: 0,
karanlık_ruh: 0,
soğuk_bakışlı: 0,
donuk: 0,
ujk_sözlü: 0,
aksi: 0,
uyuz: 0,
rahatsız_edici_sözlü: 0,
ofkeli: 0,
kuruntulu: 0,
şüphe_dolu: 0,
öfke_patlamalı: 0,
ters: 0,
uygunsuz_davranışlı: 0,
zayıf_iradeli: 0,
baskıcı: 0,
zorba: 0,
kör_inatçı: 0,
inadına: 0,
inatçı: 0,
katı_kafalı: 0,
kızgın: 0,
kısa_sinirli: 0,
agresif: 0,
sataşmacı: 0,
düşmanca: 0,
nefretli: 0,
pis_kokulu: 0,
çürük: 0,
çökmüş: 0,
ruhsuz_bakan: 0,
duygusuz_davranışlı: 0,
tatsız_davranış: 0,
itici: 0,
sevimsiz: 0,
çirkin_ruh: 0,
soğuk_ruh: 0,
karamsar_sesli: 0,
kaprisli: 0,
nazlanıcı: 0,
huysuz_tavırlı: 0,
kötü_davranışlı: 0,
tutarsız_kafana: 0,
kör_karar: 0,
akılsız: 0,
akılsızlık: 0,
mantıksızlık: 0,
sorun_çıkaran: 0,
felaket_getiren: 0,
zorluk_sunan: 0,
sıkıntı_veren: 0,
rahatsız_ruh: 0,
gaddarlık: 0,
acı_doluluk: 0,
sert_davranış: 0,
insafsız: 0,
merhametsiz: 0,
duygu_bozucu: 0,
öfke_dolu_söz: 0,
hakaretli: 0,
hakaret_dolu: 0,
küfürlü: 0,
kirletici: 0,
kötülük_saçan: 0,
bıkkın: 0,
bezdiren: 0,
bunalımlı: 0,
çöküntülü: 0,
söndürülmüş: 0,
yıkıcı: 0,
yıpratıcı: 0,
kırıcı_davranış: 0,
kaba_tavırlı: 0,
pasaklı: 0,
paslı: 0,
tozlu: 0,
pislenmiş: 0,
yırtık: 0,
bozguna_ugratıcı: 0,
çöküntü_dolu: 0,
çaresiz_ruh: 0,
karanlık_düşünce: 0,
zorlayıcı: 0,
musibet: 0,
dertli: 0,
sıkıntı_dolu: 0,
bunaltıcı: 0,
gergin_sözlü: 0,
tahripkar: 0,
çatışmacı: 0,
çekilmez: 0,
yakışıksız: 0,
aşağılayıcı: 0,
küçümseyici: 0,
//EN
brilliant: 1,
remarkable: 1,
splendid: 1,
marvelous: 1,
uplifting: 1,
encouraging: 1,
supportive: 1,
faithful: 1,
inspiring: 1,
hopeful: 1,
gentle: 1,
respectful: 1,
pleasant: 1,
compassionate: 1,
cheerful: 1,
joyful: 1,
vibrant: 1,
resourceful: 1,
trustworthy: 1,
ambitious: 1,
determined: 1,
brave: 1,
courteous: 1,
confident: 1,
balanced: 1,
harmonious: 1,
radiant: 1,
grateful: 1,
mindful: 1,
warmhearted: 1,
affectionate: 1,
devoted: 1,
flexible: 1,
open_minded: 1,
consistent: 1,
passionate: 1,
optimistic: 1,
diligent: 1,
focused: 1,
clever: 1,
brilliant_minded: 1,
sparkling: 1,
calm: 1,
peaceful: 1,
steady: 1,
fearless: 1,
sincere: 1,
bold: 1,
proud: 1,
welcoming: 1,
friendly: 1,
benevolent: 1,
forgiving: 1,
productive: 1,
creative: 1,
inventive: 1,
sharp: 1,
bright_minded: 1,
influential: 1,
motivated: 1,
determined: 1,
adaptable: 1,
generous_hearted: 1,
balanced_minded: 1,
devoted_minded: 1,
hope_giving: 1,
soulful: 1,
graceful: 1,

terrible: 0,
horrible: 0,
awful: 0,
disrespectful: 0,
rude: 0,
hostile: 0,
unfriendly: 0,
lazy: 0,
careless: 0,
reckless: 0,
thoughtless: 0,
negative: 0,
toxic: 0,
cruel: 0,
apathetic: 0,
hopeless: 0,
worthless: 0,
meaningless: 0,
messy: 0,
unorganized: 0,
jealous: 0,
greedy: 0,
selfish: 0,
untrustworthy: 0,
cowardly: 0,
irritable: 0,
annoying: 0,
frustrating: 0,
miserable: 0,
pathetic: 0,
tragic: 0,
depressing: 0,
sad: 0,
unpleasant: 0,
disappointing: 0,
unfortunate: 0,
nonsense: 0,
disturbing: 0,
offensive: 0,
aggressive: 0,
chaotic: 0,
unstable: 0,
pessimistic: 0,
doubtful: 0,
burdensome: 0,
ugly: 0,
unskilled: 0,
weak_minded: 0,
shameful: 0,
regretful: 0,
pitiful: 0,
troublesome: 0,
fearful: 0,
nervous: 0,
broken: 0,
lost: 0,
unloved: 0,
meaningless_minded: 0,
careless_minded: 0,
problematic: 0,
dull: 0,
lifeless: 0,
unmotivated: 0,
incredible: 1,
exceptional: 1,
refreshing: 1,
heartwarming: 1,
brave_hearted: 1,
open_hearted: 1,
energetic: 1,
inspired: 1,
dedicated: 1,
skilled: 1,
wise: 1,
honorable: 1,
magnificent: 1,
empowered: 1,
proactive: 1,
encouraging_spirit: 1,
thoughtful_minded: 1,
uplifted: 1,
progressive: 1,
balanced_spirit: 1,
generous_spirit: 1,
kind_hearted: 1,
determined_spirit: 1,
strong_willed: 1,
stable: 1,
caring: 1,
warm: 1,
deep_thinking: 1,
insightful: 1,
brilliant_spirit: 1,
helpful: 1,
consistent_mind: 1,
resilient: 1,
courageous: 1,
aware: 1,
driven: 1,
purposeful: 1,
focused_mind: 1,
joy_spreading: 1,
hope_spreading: 1,
kind_spirit: 1,
uplifting_energy: 1,
stable_minded: 1,
bright_souled: 1,
trust_giving: 1,
love_spreading: 1,
mind_opening: 1,
supportive_spirit: 1,
intelligent: 1,
brilliant_thinker: 1,
calming: 1,
motivating: 1,
high_spirited: 1,
efficient: 1,
empowering: 1,
loyal: 1,
reliable: 1,
steady_minded: 1,
brave_souled: 1,
glowing: 1,
harmonizing: 1,
healing: 1,
comforting: 1,

bad: 0,
unpleasant_feeling: 0,
hopeless_state: 0,
unfocused: 0,
disheartened: 0,
spiteful: 0,
grumpy: 0,
irritated: 0,
annoyed: 0,
blocked: 0,
uncreative: 0,
unmotivating: 0,
harmful: 0,
disconnected: 0,
cold_hearted: 0,
broken_spirit: 0,
weak: 0,
low_energy: 0,
unstable_minded: 0,
harsh: 0,
ruthless: 0,
unfair: 0,
dishonest: 0,
misleading: 0,
unbalanced: 0,
unhealthy: 0,
stressful: 0,
chaotic_minded: 0,
unfocused_spirit: 0,
uninspired: 0,
unhelpful: 0,
lifeless_spirit: 0,
negative_minded: 0,
hopeless_minded: 0,
empty: 0,
cold: 0,
unreliable: 0,
fear_spreading: 0,
anger_filled: 0,
resentful: 0,
moody: 0,
hostile_minded: 0,
unfriendly_spirit: 0,
dark_minded: 0,
sad_souled: 0,
worn_out: 0,
exhausted_mind: 0,
shattered: 0,
frustrated_spirit: 0,
disconnected_mind: 0,
careless_spirit: 0,
lost_minded: 0,
confused: 0,
pessimistic_minded: 0,
uncertain: 0,
fear_driven: 0,
numb: 0,
heavy_hearted: 0,
displeased: 0,
troubled: 0,
distressed: 0,
hurt: 0,
weak_spirit: 0,

}
//Vectorizing
function vectorize(tokens) {

      const vector = [0, 0, 0];
      for (let input of tokens) {
        if (vocab[input] !== undefined) vector[vocab[input]] += 1
      }
      return vector
}

function normalizeVector(vector) {
    const magnitude = Math.sqrt(vector.reduce((sum,val)=> sum + val * val ,0))
  return vector.map(val => val/magnitude)
}


//Using lib//
const testword =  normalizeVector(vectorize(Tokenizer("Hey Aira bugün napıyorsun")))
const score = neuron.process(testword)
console.log(neuron.process(score))
console.log(testword)
//Using lib//


